services:
  web:
    build:
      context: typescript/simple-mercari-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:9000
  app:
    build:
      context: .
      dockerfile: python/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/code
    environment:
      - FRONT_URL=http://localhost:3000
